background = #17120f
foreground = #fff0d8
cursor-color = #d95b32
selection-background = #d95b32
palette = 0=#17120f
palette = 1=#b8322d
palette = 2=#7b8b32
palette = 3=#c9972b
palette = 4=#315f68
palette = 5=#b84b2f
palette = 6=#4c8f8b
palette = 7=#fff0d8
palette = 8=#49362c
palette = 9=#df5b4c
palette = 10=#a6ad4e
palette = 11=#f0bd3e
palette = 12=#4b8791
palette = 13=#d46a4c
palette = 14=#70b7ae
palette = 15=#fff7e9
