mode = "dark"

background = "#10070b"
foreground = "#fff1d6"

accent = "#e33b42"
red     = "#ff4d5a"

color0  = "#10070b"
color1  = "#ff4d5a"
color2  = "#d6d84a"
color3  = "#f2c230"
color4  = "#406bb3"
color5  = "#d12a78"
color6  = "#3f78cf"
color7  = "#fff1d6"
color8  = "#3c1820"
color9  = "#ff7a6e"
color10 = "#edf06f"
color11 = "#ffe36b"
color12 = "#6c98d6"
color13 = "#ee6b9e"
color14 = "#ff9c76"
color15 = "#fff8e8"
