background = #17130e
foreground = #fff2d2
cursor-color = #d7a84b
selection-background = #d7a84b
palette = 0=#17130e
palette = 1=#d45a4f
palette = 2=#7c9a63
palette = 3=#d7a84b
palette = 4=#597896
palette = 5=#9b718f
palette = 6=#d7a84b
palette = 7=#fff2d2
palette = 8=#493b2a
palette = 9=#ed7964
palette = 10=#a6bc83
palette = 11=#f0cc72
palette = 12=#82a4c3
palette = 13=#c095b1
palette = 14=#f1c76c
palette = 15=#fffaf0
