background = #08090d
foreground = #e7edf2
cursor-color = #7897bd
selection-background = #7897bd
palette = 0=#08090d
palette = 1=#a64b4b
palette = 2=#697b70
palette = 3=#b18b5c
palette = 4=#3d526b
palette = 5=#6d6a8f
palette = 6=#7897bd
palette = 7=#d0d8de
palette = 8=#262a32
palette = 9=#d36969
palette = 10=#8ca595
palette = 11=#d6af78
palette = 12=#607c9c
palette = 13=#9a95c2
palette = 14=#9fb8d0
palette = 15=#f4f7f8
