background = #120d18
foreground = #f4f3e8
cursor-color = #a976c3
selection-background = #a976c3
palette = 0=#120d18
palette = 1=#d3290f
palette = 2=#a0de59
palette = 3=#f5c024
palette = 4=#466b5a
palette = 5=#5f2a62
palette = 6=#a976c3
palette = 7=#f4f3e8
palette = 8=#34233b
palette = 9=#f04b2f
palette = 10=#c1f47b
palette = 11=#ffe36a
palette = 12=#6e9b83
palette = 13=#bb8dd4
palette = 14=#cba9dc
palette = 15=#fffdf2
