<#
.SYNOPSIS
    Install a Neon Mary theme on Windows 11.

.DESCRIPTION
    Copies the variant's wallpaper and .theme into the per-user themes folder,
    applies the accent colour and light/dark mode, then opens the theme so
    Windows activates it.

    Everything this does is a documented, per-user (HKCU) change. Nothing is
    patched, no system file is touched, and -Revert undoes all of it.

    What this CAN theme on stock Windows 11:
      * desktop wallpaper
      * light / dark mode (apps and system, independently addressable)
      * accent colour -- taskbar, Start highlights, focus rings, title bars
      * Windows Terminal colours, installed and set active automatically

    What it CANNOT theme without patching the OS:
      * window frame chrome, the Start flyout, Explorer's own styling.
        Those need a .msstyles visual style, which Windows refuses to load
        unless you install a signature bypass such as SecureUxTheme or the
        Windhawk UXTheme hook. That is out of scope here by design: those
        tools patch theme validation and can break on feature updates.

.PARAMETER Variant
    blade-runner | crow | amelie | tron | dark-city | fifth-element |
    grand-budapest | evangelion

.PARAMETER Mode
    dark or light. Defaults to dark, except grand-budapest which is
    designed light-first and defaults to light.

.PARAMETER WallpaperStyle
    classic (default), pop-art, or street-art. Selects which wallpaper
    art treatment to install; the accent colour and light/dark mode are
    unaffected. pop-art and street-art wallpapers are mode-independent
    (wallpapers\<style>\<variant>\4k.png), unlike classic which has a
    separate image per light/dark mode.

.PARAMETER Revert
    Restore the Windows default accent behaviour, remove installed
    Neon Mary theme files, and remove the Neon Mary Windows Terminal schemes.

.PARAMETER SkipTerminal
    Do not touch Windows Terminal's settings.json.

.PARAMETER TerminalScope
    Passed through to apply-terminal.ps1. 'defaults' (default) sets the scheme
    in profiles.defaults; 'all' also overwrites per-profile colorScheme values
    that would shadow it; 'none' installs without activating.

.EXAMPLE
    .\apply-theme.ps1 -Variant grand-budapest -Mode light

.EXAMPLE
    .\apply-theme.ps1 -Revert
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [ValidateSet('blade-runner', 'crow', 'amelie', 'tron', 'dark-city',
                 'fifth-element', 'grand-budapest', 'evangelion', 'matrix',
                 'solaris', 'suspiria')]
    [string]$Variant,

    [ValidateSet('dark', 'light')]
    [string]$Mode,

    [ValidateSet('classic', 'pop-art', 'street-art')]
    [string]$WallpaperStyle = 'classic',

    [switch]$SkipTerminal,

    [ValidateSet('defaults', 'all', 'none')]
    [string]$TerminalScope = 'defaults',

    [switch]$Revert
)

$ErrorActionPreference = 'Stop'
$repoRoot   = Split-Path -Parent $PSScriptRoot
$themesDir  = Join-Path $env:LOCALAPPDATA 'Microsoft\Windows\Themes'
$installDir = Join-Path $themesDir 'NeonMary'

$accentKey    = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent'
$personalize  = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'
$dwmKey       = 'HKCU:\Software\Microsoft\Windows\DWM'

function Restart-Explorer {
    # Killing Explorer is a visible, state-changing action, so it honours
    # -WhatIf / -Confirm like any well-behaved cmdlet.
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]
    param()
    if (-not $PSCmdlet.ShouldProcess('explorer.exe', 'Restart to apply accent colour')) {
        Write-Host 'Skipped Explorer restart; sign out and in to apply the accent.'
        return
    }
    Write-Host 'Restarting Explorer so the taskbar picks up the accent...'
    Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    if (-not (Get-Process -Name explorer -ErrorAction SilentlyContinue)) {
        Start-Process explorer
    }
}

if ($Revert) {
    if ($WhatIfPreference) {
        Write-Output "WHATIF: revert Windows accent/mode registry values"
        Write-Output "WHATIF: remove installed theme directory $installDir"
        Write-Output 'WHATIF: restart Explorer to refresh the shell'
        Write-Output 'WHATIF: remove Neon Mary schemes from Windows Terminal'
        return
    }
    Write-Host 'Reverting Neon Mary Windows theming...'
    # Let Windows pick the accent from the wallpaper again, and drop the
    # accent-on-taskbar override. The palette itself is regenerated by Windows.
    Set-ItemProperty -Path $personalize -Name 'ColorPrevalence' -Value 0 -Type DWord -ErrorAction SilentlyContinue
    Set-ItemProperty -Path $dwmKey      -Name 'ColorPrevalence' -Value 0 -Type DWord -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path $accentKey -Name 'AccentPalette'   -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path $accentKey -Name 'AccentColorMenu' -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path $accentKey -Name 'StartColorMenu'  -ErrorAction SilentlyContinue
    if (Test-Path $installDir) {
        Remove-Item $installDir -Recurse -Force
        Write-Host "  removed $installDir"
    }
    Restart-Explorer
    Write-Host 'Reverted. Pick a stock theme in Settings > Personalization > Themes.'

    $wt = Join-Path $PSScriptRoot 'apply-terminal.ps1'
    if (Test-Path $wt) {
        Write-Host ''
        Write-Host 'Reverting Windows Terminal...'
        & $wt -Revert
    }
    return
}

if (-not $Variant) {
    throw 'Specify -Variant (or -Revert). See Get-Help .\apply-theme.ps1 -Full'
}
if (-not $Mode) {
    $Mode = if ($Variant -eq 'grand-budapest') { 'light' } else { 'dark' }
    Write-Host "No -Mode given; using '$Mode' for $Variant."
}

$themeSrc = Join-Path $repoRoot "windows\$Variant-$Mode.theme"
$regSrc   = Join-Path $repoRoot "windows\$Variant-$Mode.reg"
$wallSrc  = if ($WallpaperStyle -ne 'classic') {
    Join-Path $repoRoot "wallpapers\$WallpaperStyle\$Variant\4k.png"
} elseif ($Variant -eq 'blade-runner') {
    Join-Path $repoRoot "wallpapers\$Mode\4k.png"
} else {
    Join-Path $repoRoot "wallpapers\$Variant\$Mode\4k.png"
}

foreach ($f in @($themeSrc, $regSrc, $wallSrc)) {
    if (-not (Test-Path $f)) { throw "Missing required file: $f" }
}

$wallDst = Join-Path $installDir "$Variant-$Mode.jpg"

if ($WhatIfPreference) {
    Write-Output "WHATIF: copy wallpaper ($WallpaperStyle) $wallSrc -> $wallDst"
    Write-Output "WHATIF: install theme $themeSrc"
    Write-Output "WHATIF: import accent/mode registry $regSrc"
    if ($SkipTerminal) {
        Write-Output 'WHATIF: leave Windows Terminal unchanged (-SkipTerminal)'
    } else {
        Write-Output "WHATIF: install Windows Terminal scheme ($TerminalScope scope)"
    }
    Write-Output 'WHATIF: open the .theme file in Windows Personalization'
    Write-Output 'WHATIF: restart Explorer to refresh the shell'
    return
}

New-Item -ItemType Directory -Force -Path $installDir | Out-Null

# The .theme references a .jpg; Windows accepts png too, but converting keeps
# the reference honest and the file small enough to copy quickly.
Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile($wallSrc)
try {
    $img.Save($wallDst, [System.Drawing.Imaging.ImageFormat]::Jpeg)
} finally {
    $img.Dispose()
}
Write-Host "  wallpaper -> $wallDst"

$themeDst = Join-Path $installDir "$Variant-$Mode.theme"
Copy-Item $themeSrc $themeDst -Force
Write-Host "  theme     -> $themeDst"

Write-Host '  applying accent + mode...'
$reg = Start-Process -FilePath reg.exe -ArgumentList @('import', $regSrc) `
    -Wait -PassThru -WindowStyle Hidden
if ($reg.ExitCode -ne 0) { throw "reg import failed for $regSrc (exit $($reg.ExitCode))" }

# Windows Terminal is a separate config, so hand off to the dedicated script.
# -SkipTerminal opts out; a missing Windows Terminal is a warning, not a failure.
if (-not $SkipTerminal) {
    $wt = Join-Path $PSScriptRoot 'apply-terminal.ps1'
    if (Test-Path $wt) {
        Write-Host '  configuring Windows Terminal...'
        & $wt -Variant $Variant -Mode $Mode -Scope $TerminalScope
    } else {
        Write-Warning "apply-terminal.ps1 not found next to this script; skipping."
    }
}

# Opening the .theme is what makes Windows actually adopt it. Use the theme
# action directly rather than merely launching the file association (which can
# open Personalization without applying when invoked from an SSH session).
Write-Host '  applying Windows theme...'
$themeAction = "themecpl.dll,OpenThemeAction `"$themeDst`""
Start-Process -FilePath rundll32.exe -ArgumentList $themeAction -Wait

# Explicit wallpaper fallback. This also makes the result deterministic when
# the theme action is launched from a non-interactive shell. The rundll32
# helper is not sufficient by itself here: call SystemParametersInfo with
# SPI_SETDESKWALLPAPER and SPIF_UPDATEINIFILE|SPIF_SENDCHANGE.
Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name Wallpaper -Value $wallDst
if (-not ('NeonMary.Desktop' -as [type])) {
    Add-Type @'
using System;
using System.Runtime.InteropServices;
namespace NeonMary {
    public static class Desktop {
        [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        public static extern bool SystemParametersInfo(
            uint action, uint param, string file, uint flags);
    }
}
'@
}
$wallApplied = [NeonMary.Desktop]::SystemParametersInfo(20, 0, $wallDst, 3)
if (-not $wallApplied) { throw "SystemParametersInfo(SPI_SETDESKWALLPAPER) failed" }

Restart-Explorer

Write-Host ''
$styleNote = if ($WallpaperStyle -ne 'classic') { ", $WallpaperStyle wallpaper" } else { '' }
Write-Host "Applied Neon Mary - $Variant ($Mode$styleNote)."
Write-Host 'The Settings > Personalization window may open; that is expected.'
Write-Host 'Windows Terminal colours are separate:'
Write-Host "  $repoRoot\terminals\$Variant\$Mode\windows-terminal.json"
Write-Host 'Revert with:  .\apply-theme.ps1 -Revert'
