<#
.SYNOPSIS
    Install a Neon Mary theme on Windows 11.

.DESCRIPTION
    Copies the variant's wallpaper and .theme into the per-user themes folder,
    applies the accent colour and light/dark mode, then opens the theme so
    Windows activates it.

    Everything this does is a documented, per-user (HKCU) change. Nothing is
    patched, no system file is touched, and -Revert undoes all of it.

    What this CAN theme on stock Windows 11:
      * desktop wallpaper
      * light / dark mode (apps and system, independently addressable)
      * accent colour -- taskbar, Start highlights, focus rings, title bars
      * Windows Terminal colours (see ..\terminals\<variant>\)

    What it CANNOT theme without patching the OS:
      * window frame chrome, the Start flyout, Explorer's own styling.
        Those need a .msstyles visual style, which Windows refuses to load
        unless you install a signature bypass such as SecureUxTheme or the
        Windhawk UXTheme hook. That is out of scope here by design: those
        tools patch theme validation and can break on feature updates.

.PARAMETER Variant
    blade-runner | crow | amelie | tron | dark-city | fifth-element |
    grand-budapest

.PARAMETER Mode
    dark or light. Defaults to dark, except grand-budapest which is
    designed light-first and defaults to light.

.PARAMETER Revert
    Restore the Windows default accent behaviour and remove installed
    Neon Mary theme files.

.EXAMPLE
    .\apply-theme.ps1 -Variant grand-budapest -Mode light

.EXAMPLE
    .\apply-theme.ps1 -Revert
#>
[CmdletBinding()]
param(
    [ValidateSet('blade-runner', 'crow', 'amelie', 'tron', 'dark-city',
                 'fifth-element', 'grand-budapest')]
    [string]$Variant,

    [ValidateSet('dark', 'light')]
    [string]$Mode,

    [switch]$Revert
)

$ErrorActionPreference = 'Stop'
$repoRoot   = Split-Path -Parent $PSScriptRoot
$themesDir  = Join-Path $env:LOCALAPPDATA 'Microsoft\Windows\Themes'
$installDir = Join-Path $themesDir 'NeonMary'

$accentKey    = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent'
$personalize  = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'
$dwmKey       = 'HKCU:\Software\Microsoft\Windows\DWM'

function Restart-Explorer {
    # Killing Explorer is a visible, state-changing action, so it honours
    # -WhatIf / -Confirm like any well-behaved cmdlet.
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]
    param()
    if (-not $PSCmdlet.ShouldProcess('explorer.exe', 'Restart to apply accent colour')) {
        Write-Host 'Skipped Explorer restart; sign out and in to apply the accent.'
        return
    }
    Write-Host 'Restarting Explorer so the taskbar picks up the accent...'
    Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    if (-not (Get-Process -Name explorer -ErrorAction SilentlyContinue)) {
        Start-Process explorer
    }
}

if ($Revert) {
    Write-Host 'Reverting Neon Mary Windows theming...'
    # Let Windows pick the accent from the wallpaper again, and drop the
    # accent-on-taskbar override. The palette itself is regenerated by Windows.
    Set-ItemProperty -Path $personalize -Name 'ColorPrevalence' -Value 0 -Type DWord -ErrorAction SilentlyContinue
    Set-ItemProperty -Path $dwmKey      -Name 'ColorPrevalence' -Value 0 -Type DWord -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path $accentKey -Name 'AccentPalette'   -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path $accentKey -Name 'AccentColorMenu' -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path $accentKey -Name 'StartColorMenu'  -ErrorAction SilentlyContinue
    if (Test-Path $installDir) {
        Remove-Item $installDir -Recurse -Force
        Write-Host "  removed $installDir"
    }
    Restart-Explorer
    Write-Host 'Reverted. Pick a stock theme in Settings > Personalization > Themes.'
    return
}

if (-not $Variant) {
    throw 'Specify -Variant (or -Revert). See Get-Help .\apply-theme.ps1 -Full'
}
if (-not $Mode) {
    $Mode = if ($Variant -eq 'grand-budapest') { 'light' } else { 'dark' }
    Write-Host "No -Mode given; using '$Mode' for $Variant."
}

$themeSrc = Join-Path $repoRoot "windows\$Variant-$Mode.theme"
$regSrc   = Join-Path $repoRoot "windows\$Variant-$Mode.reg"
$wallSrc  = if ($Variant -eq 'blade-runner') {
    Join-Path $repoRoot "wallpapers\$Mode\4k.png"
} else {
    Join-Path $repoRoot "wallpapers\$Variant\$Mode\4k.png"
}

foreach ($f in @($themeSrc, $regSrc, $wallSrc)) {
    if (-not (Test-Path $f)) { throw "Missing required file: $f" }
}

New-Item -ItemType Directory -Force -Path $installDir | Out-Null

# The .theme references a .jpg; Windows accepts png too, but converting keeps
# the reference honest and the file small enough to copy quickly.
$wallDst = Join-Path $installDir "$Variant-$Mode.jpg"
Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile($wallSrc)
try {
    $img.Save($wallDst, [System.Drawing.Imaging.ImageFormat]::Jpeg)
} finally {
    $img.Dispose()
}
Write-Host "  wallpaper -> $wallDst"

$themeDst = Join-Path $installDir "$Variant-$Mode.theme"
Copy-Item $themeSrc $themeDst -Force
Write-Host "  theme     -> $themeDst"

Write-Host '  applying accent + mode...'
reg.exe import $regSrc 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) { throw "reg import failed for $regSrc" }

# Opening the .theme is what makes Windows actually adopt it.
Start-Process $themeDst
Start-Sleep -Seconds 3

Restart-Explorer

Write-Host ''
Write-Host "Applied Neon Mary - $Variant ($Mode)."
Write-Host 'The Settings > Personalization window may open; that is expected.'
Write-Host 'Windows Terminal colours are separate:'
Write-Host "  $repoRoot\terminals\$Variant\$Mode\windows-terminal.json"
Write-Host 'Revert with:  .\apply-theme.ps1 -Revert'
