mode = "dark"

background = "#17120f"
foreground = "#fff0d8"

accent = "#d95b32"
red     = "#b8322d"

color0  = "#17120f"
color1  = "#b8322d"
color2  = "#7b8b32"
color3  = "#c9972b"
color4  = "#315f68"
color5  = "#b84b2f"
color6  = "#4c8f8b"
color7  = "#fff0d8"
color8  = "#49362c"
color9  = "#df5b4c"
color10 = "#a6ad4e"
color11 = "#f0bd3e"
color12 = "#4b8791"
color13 = "#d46a4c"
color14 = "#70b7ae"
color15 = "#fff7e9"
