background = #08080d
foreground = #e8e3e7
cursor-color = #b7a6c9
selection-background = #b7a6c9
palette = 0=#08080d
palette = 1=#d43d55
palette = 2=#75866f
palette = 3=#b5a17b
palette = 4=#586277
palette = 5=#9b79a7
palette = 6=#9eabb7
palette = 7=#d2ccd2
palette = 8=#282832
palette = 9=#f05b6d
palette = 10=#a2b58d
palette = 11=#d2bd94
palette = 12=#78839b
palette = 13=#bd98c9
palette = 14=#c9d4dc
palette = 15=#f7f2f5
