mode = "dark"

background = "#050b12"
foreground = "#d9f7ff"

accent = "#00c8ff"
red     = "#ff4b36"

color0  = "#050b12"
color1  = "#ff4b36"
color2  = "#61d36e"
color3  = "#e7c34f"
color4  = "#147aa0"
color5  = "#8b6cff"
color6  = "#00c8ff"
color7  = "#d9f7ff"
color8  = "#18303e"
color9  = "#ff735f"
color10 = "#8bec91"
color11 = "#ffe477"
color12 = "#42b7dc"
color13 = "#b19dff"
color14 = "#62e4ff"
color15 = "#f3fdff"
