background = #10191a
foreground = #f4ead3
cursor-color = #d88a3d
selection-background = #d88a3d
palette = 0=#10191a
palette = 1=#c95a3d
palette = 2=#8c9b62
palette = 3=#d88a3d
palette = 4=#3e7180
palette = 5=#8a6470
palette = 6=#b8a06a
palette = 7=#f4ead3
palette = 8=#253536
palette = 9=#e47a53
palette = 10=#b1bd7c
palette = 11=#f0b45e
palette = 12=#6c9eaa
palette = 13=#b18a99
palette = 14=#e0b06a
palette = 15=#fff8e6
