background = #100d0d
foreground = #f3eee0
cursor-color = #c93532
selection-background = #c93532
palette = 0=#100d0d
palette = 1=#e4473f
palette = 2=#5f8692
palette = 3=#d0a83c
palette = 4=#41677a
palette = 5=#8f3f45
palette = 6=#b65b42
palette = 7=#f3eee0
palette = 8=#332322
palette = 9=#f47763
palette = 10=#92b6bc
palette = 11=#ecd06b
palette = 12=#6e9aaa
palette = 13=#c2767a
palette = 14=#e4b36a
palette = 15=#fff9e8
