background = #050b12
foreground = #d9f7ff
cursor-color = #00c8ff
selection-background = #00c8ff
palette = 0=#050b12
palette = 1=#ff4b36
palette = 2=#61d36e
palette = 3=#e7c34f
palette = 4=#147aa0
palette = 5=#8b6cff
palette = 6=#00c8ff
palette = 7=#d9f7ff
palette = 8=#18303e
palette = 9=#ff735f
palette = 10=#8bec91
palette = 11=#ffe477
palette = 12=#42b7dc
palette = 13=#b19dff
palette = 14=#62e4ff
palette = 15=#f3fdff
