background = #f3eee3
foreground = #241c1b
cursor-color = #a52e2f
selection-background = #a52e2f
palette = 0=#f3eee3
palette = 1=#972c2d
palette = 2=#3e6974
palette = 3=#8a620e
palette = 4=#31536a
palette = 5=#713c42
palette = 6=#8e4a39
palette = 7=#241c1b
palette = 8=#b8aaa0
palette = 9=#bd4b4d
palette = 10=#668994
palette = 11=#af861d
palette = 12=#52788a
palette = 13=#985f65
palette = 14=#b27a3d
palette = 15=#241c1b
