background = #080d14
foreground = #f5eee2
cursor-color = #ef3b24
selection-background = #ef3b24
palette = 0=#080d14
palette = 1=#ff5142
palette = 2=#4dc4d8
palette = 3=#f3b72b
palette = 4=#2369a0
palette = 5=#b62d68
palette = 6=#16a9d1
palette = 7=#f5eee2
palette = 8=#182333
palette = 9=#ff806b
palette = 10=#83e3e8
palette = 11=#ffd96b
palette = 12=#55a2ce
palette = 13=#ed6b9a
palette = 14=#ff9a73
palette = 15=#fffaf0
