background = #fff4df
foreground = #241116
cursor-color = #a51f3c
selection-background = #a51f3c
palette = 0=#fff4df
palette = 1=#9f1729
palette = 2=#58720d
palette = 3=#9b6900
palette = 4=#23558e
palette = 5=#7d204b
palette = 6=#1c5da8
palette = 7=#241116
palette = 8=#b28f8d
palette = 9=#c44343
palette = 10=#78942f
palette = 11=#b18416
palette = 12=#4776a9
palette = 13=#a34b76
palette = 14=#ad4b43
palette = 15=#241116
