mode = "light"

background = "#f5eedf"
foreground = "#2c2418"

accent = "#9c6a18"
red     = "#a63e36"

color0  = "#f5eedf"
color1  = "#a63e36"
color2  = "#4e713b"
color3  = "#9c6a18"
color4  = "#3c607a"
color5  = "#76506d"
color6  = "#9c6a18"
color7  = "#2c2418"
color8  = "#c9bca6"
color9  = "#c45b4f"
color10 = "#729559"
color11 = "#bd8d28"
color12 = "#6387a2"
color13 = "#98728e"
color14 = "#76500f"
color15 = "#2c2418"
