mode = "dark"

background = "#08090d"
foreground = "#e7edf2"

accent = "#7897bd"
red     = "#a64b4b"

color0  = "#08090d"
color1  = "#a64b4b"
color2  = "#697b70"
color3  = "#b18b5c"
color4  = "#3d526b"
color5  = "#6d6a8f"
color6  = "#7897bd"
color7  = "#d0d8de"
color8  = "#262a32"
color9  = "#d36969"
color10 = "#8ca595"
color11 = "#d6af78"
color12 = "#607c9c"
color13 = "#9a95c2"
color14 = "#9fb8d0"
color15 = "#f4f7f8"
