mode = "dark"

background = "#10191a"
foreground = "#f4ead3"

accent = "#d88a3d"
red     = "#c95a3d"

color0  = "#10191a"
color1  = "#c95a3d"
color2  = "#8c9b62"
color3  = "#d88a3d"
color4  = "#3e7180"
color5  = "#8a6470"
color6  = "#b8a06a"
color7  = "#f4ead3"
color8  = "#253536"
color9  = "#e47a53"
color10 = "#b1bd7c"
color11 = "#f0b45e"
color12 = "#6c9eaa"
color13 = "#b18a99"
color14 = "#e0b06a"
color15 = "#fff8e6"
