mode = "dark"

background = "#080d14"
foreground = "#f5eee2"

accent = "#ef3b24"
red     = "#ff5142"

color0  = "#080d14"
color1  = "#ff5142"
color2  = "#4dc4d8"
color3  = "#f3b72b"
color4  = "#2369a0"
color5  = "#b62d68"
color6  = "#16a9d1"
color7  = "#f5eee2"
color8  = "#182333"
color9  = "#ff806b"
color10 = "#83e3e8"
color11 = "#ffd96b"
color12 = "#55a2ce"
color13 = "#ed6b9a"
color14 = "#ff9a73"
color15 = "#fffaf0"
