mode = "dark"

background = "#120d18"
foreground = "#f4f3e8"

accent = "#a976c3"
red     = "#d3290f"

color0  = "#120d18"
color1  = "#d3290f"
color2  = "#a0de59"
color3  = "#f5c024"
color4  = "#466b5a"
color5  = "#5f2a62"
color6  = "#a976c3"
color7  = "#f4f3e8"
color8  = "#34233b"
color9  = "#f04b2f"
color10 = "#c1f47b"
color11 = "#ffe36a"
color12 = "#6e9b83"
color13 = "#bb8dd4"
color14 = "#cba9dc"
color15 = "#fffdf2"
