background = #100b16
foreground = #fff0de
cursor-color = #00cce8
selection-background = #00cce8
palette = 0=#100b16
palette = 1=#ff643e
palette = 2=#62d88a
palette = 3=#f5c842
palette = 4=#2874b8
palette = 5=#d04fc1
palette = 6=#00cce8
palette = 7=#fff0de
palette = 8=#38253e
palette = 9=#ff9478
palette = 10=#98f0ae
palette = 11=#ffe27b
palette = 12=#62a5e8
palette = 13=#ee86df
palette = 14=#75f3ff
palette = 15=#fff8ed
