background = #07120b
foreground = #d9ffe1
cursor-color = #39ff88
selection-background = #39ff88
palette = 0=#07120b
palette = 1=#ff5c62
palette = 2=#39d353
palette = 3=#d7d34e
palette = 4=#318b58
palette = 5=#9a7cff
palette = 6=#39ff88
palette = 7=#d9ffe1
palette = 8=#1b3d27
palette = 9=#ff8589
palette = 10=#78ff9d
palette = 11=#f2ef78
palette = 12=#61bd82
palette = 13=#b9a7ff
palette = 14=#8affb8
palette = 15=#f2fff4
